### ISSUE TITLE
problème icon 

### ISSUE THREAD

**Issue by LucasB25** [Linedev-Azuriom/Plugin_Staff#3]
![image](https://user-images.githubusercontent.com/50886682/192760426-c2ea8336-5bc0-47a4-bbfd-94f055d38684.png)
il est possible de mettre des icons

et il Nis n'a aucun message d'erreur

**Comment by Prozoon700** [comment]
Hi.
Sorry for commenting in english, I don't know French 😅.

I have uploaded a fix for that problem [here](https://github.com/Linedev-Azuriom/Plugin_Staff/issues/7#issuecomment-2094209178) if you wish to check it.

Have a good day!

**Comment by Linedev-Web** [comment]
Thanks, fix PR: https://github.com/Linedev-Azuriom/Plugin_Staff/pull/8
