### ISSUE TITLE
Bug Ranking page

### ISSUE THREAD

**Issue by Blackbalrog** [Linedev-Azuriom/Plugin_Staff#6]
Hi,

I noticed that when you create a staff and when I want to move it in the list of staff, the staff page does not move.
I contacted you by discord with a video as proof.

Cordially,

**Comment by Prozoon700** [comment]
Do you still need help?

**Comment by Linedev-Web** [comment]
Thanks, fix PR: https://github.com/Linedev-Azuriom/Plugin_Staff/pull/8
